services:
  model_endpoint:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: model_endpoint
    volumes:
      - "./../train/results:/app/results"
    ports:
      - "5000:5000"
